
<!DOCTYPE pedido [
        <!ELEMENT pedido (destinatario|articulo|direccion|entrega)*>
        <!ELEMENT destinatario (#PCDATA)>
        <!ELEMENT articulo (#PCDATA)>
        <!ELEMENT direccion (#PCDATA)>
        <!ELEMENT entrega (#PCDATA)>
        ]>

<pedido>
    <destinatario> Sr. Juan Delgado Mart√≠nez </destinatario>
    <articulo> Bicicleta Bianchi Oltre </articulo>
    <direccion> Reforma 423, tercer piso, letra A </direccion>
    <entrega> 19-09-2021 </entrega>
</pedido>
