<?xml version="1.0"?>
<!DOCTYPE documento [
        <!ELEMENT documento (p|u|t)*>
        <!ELEMENT p (#PCDATA|destacar)*>
        <!ELEMENT destacar (#PCDATA)>
        <!ATTLIST destacar
                importancia CDATA #REQUIRED>
        <!ELEMENT u (#PCDATA)>
        <!ELEMENT t (#PCDATA|imagen)*>
        <!ELEMENT imagen EMPTY>
        <!ATTLIST imagen
                fichero CDATA #REQUIRED>
        ]>
<documento>
    <p>Mi Primer <destacar importancia="1">documentoXML</destacar></p>
    <u>Comienza con la etiqueta <![CDATA[<documento>]]> </u>
    <t>A continuaci√≥n colocamos un elemento sin contenido <imagen fichero="imagen.gif"/></t>
</documento>
